// <auto-generated />
using System;
using FileService.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileService.Migrations
{
    [DbContext(typeof(FileServiceDbContext))]
    [Migration("20251116130537_AddApiSignaturesTable")]
    partial class AddApiSignaturesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileService.Repositories.Entities.ApiSignature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AllowedFileTypes")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("allowed_file_types");

                    b.Property<string>("AllowedOperation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("allowed_operation");

                    b.Property<string>("CallerService")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("caller_service");

                    b.Property<string>("CallerServiceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("caller_service_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("CreatorIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("creator_ip");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<long?>("MaxFileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("max_file_size");

                    b.Property<int>("MaxUsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("max_usage_count");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("RevokeReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("revoke_reason");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("SignatureToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("signature_token");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("usage_count");

                    b.HasKey("Id")
                        .HasName("pk_api_signatures");

                    b.HasIndex("CallerService")
                        .HasDatabaseName("IX_ApiSignatures_CallerService");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_ApiSignatures_CreatedAt");

                    b.HasIndex("SignatureToken")
                        .IsUnique()
                        .HasDatabaseName("IX_ApiSignatures_SignatureToken_Unique");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("IX_ApiSignatures_Status_ExpiresAt");

                    b.ToTable("api_signatures", (string)null);
                });

            modelBuilder.Entity("FileService.Repositories.Entities.UploadedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()")
                        .HasComment("主键ID");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bucket_name")
                        .HasComment("存储桶名称");

                    b.Property<DateTimeOffset>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'")
                        .HasComment("创建时间");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted")
                        .HasComment("逻辑删除标志");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("file_hash")
                        .HasComment("文件SHA256哈希值，用于去重");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_key")
                        .HasComment("文件存储路径");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("file_url")
                        .HasComment("文件访问URL");

                    b.Property<DateTimeOffset>("LastAccessTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_access_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'")
                        .HasComment("最后访问时间");

                    b.Property<int>("ReferenceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("reference_count")
                        .HasComment("文件引用计数");

                    b.Property<int>("UploadStatus")
                        .HasColumnType("integer")
                        .HasColumnName("upload_status")
                        .HasComment("上传状态");

                    b.Property<string>("UploaderId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("uploader_id")
                        .HasComment("上传者用户ID");

                    b.HasKey("Id")
                        .HasName("pk_uploaded_files");

                    b.HasIndex("CreateTime")
                        .IsDescending()
                        .HasDatabaseName("IX_UploadedFiles_CreateTime");

                    b.HasIndex("Deleted")
                        .HasDatabaseName("IX_UploadedFiles_Deleted");

                    b.HasIndex("FileHash")
                        .IsUnique()
                        .HasDatabaseName("IX_UploadedFiles_FileHash_Unique")
                        .HasFilter("\"deleted\" = false");

                    b.HasIndex("UploadStatus")
                        .HasDatabaseName("IX_UploadedFiles_UploadStatus");

                    b.HasIndex("UploaderId")
                        .HasDatabaseName("IX_UploadedFiles_UploaderId");

                    b.HasIndex("UploaderId", "Deleted", "CreateTime")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_UploadedFiles_UploaderId_Deleted_CreateTime");

                    b.HasIndex(new[] { "CreateTime" }, "IX_UploadedFiles_CreateTime")
                        .HasDatabaseName("ix_uploaded_files_create_time");

                    b.HasIndex(new[] { "Deleted" }, "IX_UploadedFiles_Deleted")
                        .HasDatabaseName("ix_uploaded_files_deleted");

                    b.HasIndex(new[] { "FileHash" }, "IX_UploadedFiles_FileHash_Unique")
                        .IsUnique()
                        .HasDatabaseName("ix_uploaded_files_file_hash");

                    b.HasIndex(new[] { "UploadStatus" }, "IX_UploadedFiles_UploadStatus")
                        .HasDatabaseName("ix_uploaded_files_upload_status");

                    b.HasIndex(new[] { "UploaderId" }, "IX_UploadedFiles_UploaderId")
                        .HasDatabaseName("ix_uploaded_files_uploader_id");

                    b.HasIndex(new[] { "UploaderId", "Deleted", "CreateTime" }, "IX_UploadedFiles_UploaderId_Deleted_CreateTime")
                        .HasDatabaseName("ix_uploaded_files_uploader_id_deleted_create_time");

                    b.ToTable("uploaded_files", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
