// <auto-generated />
using System;
using FileService.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileService.Migrations
{
    [DbContext(typeof(FileServiceDbContext))]
    [Migration("20251111104912_InitialCreateWithNewSchema")]
    partial class InitialCreateWithNewSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileService.Repositories.Entities.Bucket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()")
                        .HasComment("主键ID");

                    b.Property<DateTimeOffset>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description")
                        .HasComment("存储桶描述");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled")
                        .HasComment("是否启用");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name")
                        .HasComment("存储桶名称");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id")
                        .HasComment("所属服务ID");

                    b.Property<DateTimeOffset>("UpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'")
                        .HasComment("更新时间");

                    b.HasKey("Id")
                        .HasName("pk_buckets");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Buckets_Name_Unique");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("IX_Buckets_ServiceId");

                    b.HasIndex(new[] { "Name" }, "IX_Buckets_Name_Unique")
                        .IsUnique()
                        .HasDatabaseName("ix_buckets_name");

                    b.HasIndex(new[] { "ServiceId" }, "IX_Buckets_ServiceId")
                        .HasDatabaseName("ix_buckets_service_id");

                    b.ToTable("buckets", (string)null);
                });

            modelBuilder.Entity("FileService.Repositories.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()")
                        .HasComment("主键ID");

                    b.Property<DateTimeOffset>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description")
                        .HasComment("服务描述");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled")
                        .HasComment("是否启用");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name")
                        .HasComment("服务名称");

                    b.Property<DateTimeOffset>("UpdateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'")
                        .HasComment("更新时间");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Services_Name_Unique");

                    b.HasIndex(new[] { "Name" }, "IX_Services_Name_Unique")
                        .IsUnique()
                        .HasDatabaseName("ix_services_name");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("FileService.Repositories.Entities.UploadedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()")
                        .HasComment("主键ID");

                    b.Property<Guid>("BucketId")
                        .HasColumnType("uuid")
                        .HasColumnName("bucket_id")
                        .HasComment("所属存储桶ID");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type")
                        .HasComment("文件MIME类型");

                    b.Property<DateTimeOffset>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'")
                        .HasComment("创建时间");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted")
                        .HasComment("逻辑删除标志");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("file_extension")
                        .HasComment("文件扩展名");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("file_hash")
                        .HasComment("文件SHA256哈希值，用于去重");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_key")
                        .HasComment("文件存储路径");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size")
                        .HasComment("文件大小（字节）");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("file_url")
                        .HasComment("文件访问URL");

                    b.Property<DateTimeOffset>("LastAccessTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_access_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'")
                        .HasComment("最后访问时间");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name")
                        .HasComment("原始文件名称");

                    b.Property<int>("ReferenceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("reference_count")
                        .HasComment("文件引用计数");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id")
                        .HasComment("所属服务ID");

                    b.Property<string>("UploaderId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("uploader_id")
                        .HasComment("上传者用户ID");

                    b.HasKey("Id")
                        .HasName("pk_uploaded_files");

                    b.HasIndex("BucketId")
                        .HasDatabaseName("ix_uploaded_files_bucket_id");

                    b.HasIndex("ContentType")
                        .HasDatabaseName("IX_UploadedFiles_ContentType");

                    b.HasIndex("CreateTime")
                        .HasDatabaseName("IX_UploadedFiles_CreateTime");

                    b.HasIndex("Deleted")
                        .HasDatabaseName("IX_UploadedFiles_Deleted");

                    b.HasIndex("FileHash")
                        .IsUnique()
                        .HasDatabaseName("IX_UploadedFiles_FileHash_Unique")
                        .HasFilter("\"deleted\" = false");

                    b.HasIndex("ReferenceCount")
                        .HasDatabaseName("IX_UploadedFiles_ReferenceCount");

                    b.HasIndex("UploaderId")
                        .HasDatabaseName("IX_UploadedFiles_UploaderId");

                    b.HasIndex("Deleted", "UploaderId")
                        .HasDatabaseName("IX_UploadedFiles_Deleted_UploaderId");

                    b.HasIndex("ServiceId", "BucketId")
                        .HasDatabaseName("IX_UploadedFiles_ServiceId_BucketId");

                    b.HasIndex("ContentType", "CreateTime", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("IX_UploadedFiles_ContentType_CreateTime_Id_Desc");

                    b.HasIndex("UploaderId", "CreateTime", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("IX_UploadedFiles_UploaderId_CreateTime_Id_Desc");

                    b.HasIndex(new[] { "ContentType" }, "IX_UploadedFiles_ContentType")
                        .HasDatabaseName("ix_uploaded_files_content_type");

                    b.HasIndex(new[] { "ContentType", "CreateTime", "Id" }, "IX_UploadedFiles_ContentType_CreateTime_Id_Desc")
                        .HasDatabaseName("ix_uploaded_files_content_type_create_time_id");

                    b.HasIndex(new[] { "CreateTime" }, "IX_UploadedFiles_CreateTime")
                        .HasDatabaseName("ix_uploaded_files_create_time");

                    b.HasIndex(new[] { "Deleted" }, "IX_UploadedFiles_Deleted")
                        .HasDatabaseName("ix_uploaded_files_deleted");

                    b.HasIndex(new[] { "Deleted", "UploaderId" }, "IX_UploadedFiles_Deleted_UploaderId")
                        .HasDatabaseName("ix_uploaded_files_deleted_uploader_id");

                    b.HasIndex(new[] { "FileHash" }, "IX_UploadedFiles_FileHash_Unique")
                        .IsUnique()
                        .HasDatabaseName("ix_uploaded_files_file_hash");

                    b.HasIndex(new[] { "ReferenceCount" }, "IX_UploadedFiles_ReferenceCount")
                        .HasDatabaseName("ix_uploaded_files_reference_count");

                    b.HasIndex(new[] { "ServiceId", "BucketId" }, "IX_UploadedFiles_ServiceId_BucketId")
                        .HasDatabaseName("ix_uploaded_files_service_id_bucket_id");

                    b.HasIndex(new[] { "UploaderId" }, "IX_UploadedFiles_UploaderId")
                        .HasDatabaseName("ix_uploaded_files_uploader_id");

                    b.HasIndex(new[] { "UploaderId", "CreateTime", "Id" }, "IX_UploadedFiles_UploaderId_CreateTime_Id_Desc")
                        .HasDatabaseName("ix_uploaded_files_uploader_id_create_time_id");

                    b.ToTable("uploaded_files", (string)null);
                });

            modelBuilder.Entity("FileService.Repositories.Entities.Bucket", b =>
                {
                    b.HasOne("FileService.Repositories.Entities.Service", "Service")
                        .WithMany("Buckets")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_buckets_services_service_id");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("FileService.Repositories.Entities.UploadedFile", b =>
                {
                    b.HasOne("FileService.Repositories.Entities.Bucket", "Bucket")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("BucketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_uploaded_files_buckets_bucket_id");

                    b.HasOne("FileService.Repositories.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_uploaded_files_services_service_id");

                    b.Navigation("Bucket");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("FileService.Repositories.Entities.Bucket", b =>
                {
                    b.Navigation("UploadedFiles");
                });

            modelBuilder.Entity("FileService.Repositories.Entities.Service", b =>
                {
                    b.Navigation("Buckets");
                });
#pragma warning restore 612, 618
        }
    }
}
